import type { QuestMeta } from "./types";
import { toSlug, wikiUrl } from "./slug";

type RawQuest = Omit<QuestMeta, "slug" | "wikiUrl"> & {
  slug?: string;
  wikiUrl?: string;
};

function q(raw: RawQuest): QuestMeta {
  return {
    ...raw,
    slug: raw.slug ?? toSlug(raw.name),
    wikiUrl: raw.wikiUrl ?? wikiUrl(raw.name),
  };
}

// Source: https://oldschool.runescape.wiki/w/Quests/List
// Difficulty and members status mirror the wiki's classification.
export const QUESTS: QuestMeta[] = [
  // ===== Free-to-play =====
  q({ name: "Below Ice Mountain", members: false, difficulty: "Novice" }),
  q({ name: "Black Knights' Fortress", members: false, difficulty: "Intermediate" }),
  q({ name: "Cook's Assistant", members: false, difficulty: "Novice" }),
  q({ name: "Demon Slayer", members: false, difficulty: "Novice" }),
  q({ name: "Doric's Quest", members: false, difficulty: "Novice" }),
  q({ name: "Dragon Slayer I", members: false, difficulty: "Experienced" }),
  q({ name: "Ernest the Chicken", members: false, difficulty: "Novice" }),
  q({ name: "Goblin Diplomacy", members: false, difficulty: "Novice" }),
  q({ name: "Imp Catcher", members: false, difficulty: "Novice" }),
  q({ name: "Learning the Ropes", members: false, difficulty: "Novice" }),
  q({ name: "Misthalin Mystery", members: false, difficulty: "Novice" }),
  q({ name: "Pirate's Treasure", members: false, difficulty: "Novice" }),
  q({ name: "Prince Ali Rescue", members: false, difficulty: "Novice" }),
  q({ name: "Romeo & Juliet", members: false, difficulty: "Novice" }),
  q({ name: "Rune Mysteries", members: false, difficulty: "Novice" }),
  q({ name: "Sheep Shearer", members: false, difficulty: "Novice" }),
  q({ name: "Shield of Arrav", members: false, difficulty: "Novice" }),
  q({ name: "The Corsair Curse", members: false, difficulty: "Intermediate" }),
  q({ name: "The Ides of Milk", members: false, difficulty: "Novice" }),
  q({ name: "The Knight's Sword", members: false, difficulty: "Intermediate" }),
  q({ name: "The Restless Ghost", members: false, difficulty: "Novice" }),
  q({ name: "Vampyre Slayer", members: false, difficulty: "Intermediate" }),
  q({ name: "Witch's Potion", members: false, difficulty: "Novice" }),
  q({ name: "X Marks the Spot", members: false, difficulty: "Novice" }),

  // ===== Members =====
  q({ name: "A Kingdom Divided", members: true, difficulty: "Experienced" }),
  q({ name: "A Night at the Theatre", members: true, difficulty: "Master" }),
  q({ name: "A Porcine of Interest", members: true, difficulty: "Novice" }),
  q({ name: "A Soul's Bane", members: true, difficulty: "Intermediate" }),
  q({ name: "A Tail of Two Cats", members: true, difficulty: "Intermediate" }),
  q({ name: "A Taste of Hope", members: true, difficulty: "Experienced" }),
  q({ name: "Animal Magnetism", members: true, difficulty: "Intermediate" }),
  q({ name: "Another Slice of H.A.M.", members: true, difficulty: "Intermediate" }),
  q({ name: "At First Light", members: true, difficulty: "Intermediate" }),
  q({ name: "Beneath Cursed Sands", members: true, difficulty: "Master" }),
  q({ name: "Between a Rock...", members: true, difficulty: "Experienced" }),
  q({ name: "Big Chompy Bird Hunting", members: true, difficulty: "Intermediate" }),
  q({ name: "Biohazard", members: true, difficulty: "Novice" }),
  q({ name: "Bone Voyage", members: true, difficulty: "Intermediate" }),
  q({ name: "Cabin Fever", members: true, difficulty: "Experienced" }),
  q({ name: "Children of the Sun", members: true, difficulty: "Novice" }),
  q({ name: "Client of Kourend", members: true, difficulty: "Novice" }),
  q({ name: "Clock Tower", members: true, difficulty: "Novice" }),
  q({ name: "Cold War", members: true, difficulty: "Intermediate" }),
  q({ name: "Contact!", members: true, difficulty: "Experienced" }),
  q({ name: "Creature of Fenkenstrain", members: true, difficulty: "Intermediate" }),
  q({ name: "Current Affairs", members: true, difficulty: "Novice" }),
  q({ name: "Darkness of Hallowvale", members: true, difficulty: "Experienced" }),
  q({ name: "Death on the Isle", members: true, difficulty: "Intermediate" }),
  q({ name: "Death Plateau", members: true, difficulty: "Novice" }),
  q({ name: "Death to the Dorgeshuun", members: true, difficulty: "Intermediate" }),
  q({ name: "Defender of Varrock", members: true, difficulty: "Experienced" }),
  q({ name: "Desert Treasure I", members: true, difficulty: "Master" }),
  q({ name: "Desert Treasure II - The Fallen Empire", members: true, difficulty: "Grandmaster" }),
  q({ name: "Devious Minds", members: true, difficulty: "Experienced" }),
  q({ name: "Dragon Slayer II", members: true, difficulty: "Grandmaster" }),
  q({ name: "Dream Mentor", members: true, difficulty: "Master" }),
  q({ name: "Druidic Ritual", members: true, difficulty: "Novice" }),
  q({ name: "Dwarf Cannon", members: true, difficulty: "Novice" }),
  q({ name: "Eadgar's Ruse", members: true, difficulty: "Intermediate" }),
  q({ name: "Eagles' Peak", members: true, difficulty: "Novice" }),
  q({ name: "Elemental Workshop I", members: true, difficulty: "Novice" }),
  q({ name: "Elemental Workshop II", members: true, difficulty: "Intermediate" }),
  q({ name: "Enakhra's Lament", members: true, difficulty: "Experienced" }),
  q({ name: "Enlightened Journey", members: true, difficulty: "Intermediate" }),
  q({ name: "Ethically Acquired Antiquities", members: true, difficulty: "Novice" }),
  q({ name: "Fairytale I - Growing Pains", members: true, difficulty: "Intermediate" }),
  q({ name: "Fairytale II - Cure a Queen", members: true, difficulty: "Experienced" }),
  q({ name: "Family Crest", members: true, difficulty: "Experienced" }),
  q({ name: "Fight Arena", members: true, difficulty: "Intermediate" }),
  q({ name: "Fishing Contest", members: true, difficulty: "Novice" }),
  q({ name: "Forgettable Tale...", members: true, difficulty: "Intermediate" }),
  q({ name: "Garden of Tranquillity", members: true, difficulty: "Intermediate" }),
  q({ name: "Gertrude's Cat", members: true, difficulty: "Novice" }),
  q({ name: "Getting Ahead", members: true, difficulty: "Intermediate" }),
  q({ name: "Ghosts Ahoy", members: true, difficulty: "Intermediate" }),
  q({ name: "Grim Tales", members: true, difficulty: "Master" }),
  q({ name: "Hazeel Cult", members: true, difficulty: "Novice" }),
  q({ name: "Heroes' Quest", members: true, difficulty: "Experienced" }),
  q({ name: "Holy Grail", members: true, difficulty: "Intermediate" }),
  q({ name: "Icthlarin's Little Helper", members: true, difficulty: "Intermediate" }),
  q({ name: "In Aid of the Myreque", members: true, difficulty: "Intermediate" }),
  q({ name: "In Search of the Myreque", members: true, difficulty: "Intermediate" }),
  q({ name: "Jungle Potion", members: true, difficulty: "Novice" }),
  q({ name: "King's Ransom", members: true, difficulty: "Experienced" }),
  q({ name: "Legends' Quest", members: true, difficulty: "Master" }),
  q({ name: "Lost City", members: true, difficulty: "Intermediate" }),
  q({ name: "Lunar Diplomacy", members: true, difficulty: "Experienced" }),
  q({ name: "Making Friends with My Arm", members: true, difficulty: "Master" }),
  q({ name: "Making History", members: true, difficulty: "Intermediate" }),
  q({ name: "Meat and Greet", members: true, difficulty: "Experienced" }),
  q({ name: "Merlin's Crystal", members: true, difficulty: "Intermediate" }),
  q({ name: "Monk's Friend", members: true, difficulty: "Novice" }),
  q({ name: "Monkey Madness I", members: true, difficulty: "Master" }),
  q({ name: "Monkey Madness II", members: true, difficulty: "Grandmaster" }),
  q({ name: "Mountain Daughter", members: true, difficulty: "Intermediate" }),
  q({ name: "Mourning's End Part I", members: true, difficulty: "Master" }),
  q({ name: "Mourning's End Part II", members: true, difficulty: "Master" }),
  q({ name: "Murder Mystery", members: true, difficulty: "Novice" }),
  q({ name: "My Arm's Big Adventure", members: true, difficulty: "Experienced" }),
  q({ name: "Nature Spirit", members: true, difficulty: "Intermediate" }),
  q({ name: "Observatory Quest", members: true, difficulty: "Intermediate" }),
  q({ name: "Olaf's Quest", members: true, difficulty: "Intermediate" }),
  q({ name: "One Small Favour", members: true, difficulty: "Experienced" }),
  q({ name: "Pandemonium", members: true, difficulty: "Novice" }),
  q({ name: "Perilous Moons", members: true, difficulty: "Master" }),
  q({ name: "Plague City", members: true, difficulty: "Novice" }),
  q({ name: "Priest in Peril", members: true, difficulty: "Novice" }),
  q({ name: "Prying Times", members: true, difficulty: "Intermediate" }),
  q({ name: "Rag and Bone Man I", members: true, difficulty: "Novice" }),
  q({ name: "Rag and Bone Man II", members: true, difficulty: "Experienced" }),
  q({ name: "Ratcatchers", members: true, difficulty: "Intermediate" }),
  q({ name: "Recipe for Disaster", members: true, difficulty: "Special" }),
  q({ name: "Recipe for Disaster: Another Cook's Quest", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Another Cook's Quest") }),
  q({ name: "Recipe for Disaster: Freeing the Goblin Generals", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Freeing the Goblin generals") }),
  q({ name: "Recipe for Disaster: Freeing the Mountain Dwarf", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Freeing the Mountain Dwarf") }),
  q({ name: "Recipe for Disaster: Freeing Evil Dave", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Freeing Evil Dave") }),
  q({ name: "Recipe for Disaster: Freeing Pirate Pete", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Freeing Pirate Pete") }),
  q({ name: "Recipe for Disaster: Freeing the Lumbridge Guide", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Freeing the Lumbridge Guide") }),
  q({ name: "Recipe for Disaster: Freeing King Awowogei", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Freeing King Awowogei") }),
  q({ name: "Recipe for Disaster: Freeing Sir Amik Varze", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Freeing Sir Amik Varze") }),
  q({ name: "Recipe for Disaster: Freeing Skrach Uglogwee", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Freeing Skrach Uglogwee") }),
  q({ name: "Recipe for Disaster: Defeating the Culinaromancer", members: true, difficulty: "Special", wikiUrl: wikiUrl("Recipe for Disaster/Defeating the Culinaromancer") }),
  q({ name: "Recruitment Drive", members: true, difficulty: "Novice" }),
  q({ name: "Regicide", members: true, difficulty: "Experienced" }),
  q({ name: "Roving Elves", members: true, difficulty: "Experienced" }),
  q({ name: "Royal Trouble", members: true, difficulty: "Experienced" }),
  q({ name: "Rum Deal", members: true, difficulty: "Experienced" }),
  q({ name: "Scorpion Catcher", members: true, difficulty: "Intermediate" }),
  q({ name: "Sea Slug", members: true, difficulty: "Intermediate" }),
  q({ name: "Secrets of the North", members: true, difficulty: "Master" }),
  q({ name: "Shadow of the Storm", members: true, difficulty: "Intermediate" }),
  q({ name: "Sheep Herder", members: true, difficulty: "Novice" }),
  q({ name: "Shilo Village", members: true, difficulty: "Intermediate" }),
  q({ name: "Sins of the Father", members: true, difficulty: "Master" }),
  q({ name: "Sleeping Giants", members: true, difficulty: "Intermediate" }),
  q({ name: "Throne of Miscellania", members: true, difficulty: "Experienced" }),
  q({ name: "Glorious Memories", members: true, difficulty: "Master" }),
  q({ name: "Land of the Goblins", members: true, difficulty: "Experienced" }),
  q({ name: "Song of the Elves", members: true, difficulty: "Grandmaster" }),
  q({ name: "Spirits of the Elid", members: true, difficulty: "Intermediate" }),
  q({ name: "Swan Song", members: true, difficulty: "Master" }),
  q({ name: "Tai Bwo Wannai Trio", members: true, difficulty: "Intermediate" }),
  q({ name: "Tale of the Righteous", members: true, difficulty: "Intermediate" }),
  q({ name: "Tears of Guthix", members: true, difficulty: "Intermediate" }),
  q({ name: "Temple of Ikov", members: true, difficulty: "Intermediate" }),
  q({ name: "Temple of the Eye", members: true, difficulty: "Intermediate" }),
  q({ name: "The Curse of Arrav", members: true, difficulty: "Master" }),
  q({ name: "The Depths of Despair", members: true, difficulty: "Intermediate" }),
  q({ name: "The Dig Site", members: true, difficulty: "Intermediate" }),
  q({ name: "The Eyes of Glouphrie", members: true, difficulty: "Intermediate" }),
  q({ name: "The Feud", members: true, difficulty: "Intermediate" }),
  q({ name: "The Final Dawn", members: true, difficulty: "Master" }),
  q({ name: "The Fremennik Exiles", members: true, difficulty: "Master" }),
  q({ name: "The Fremennik Isles", members: true, difficulty: "Experienced" }),
  q({ name: "The Fremennik Trials", members: true, difficulty: "Experienced" }),
  q({ name: "The Garden of Death", members: true, difficulty: "Intermediate" }),
  q({ name: "The Giant Dwarf", members: true, difficulty: "Intermediate" }),
  q({ name: "The Golem", members: true, difficulty: "Intermediate" }),
  q({ name: "The Grand Tree", members: true, difficulty: "Intermediate" }),
  q({ name: "The Great Brain Robbery", members: true, difficulty: "Experienced" }),
  q({ name: "The Hand in the Sand", members: true, difficulty: "Intermediate" }),
  q({ name: "The Haunted Mine", members: true, difficulty: "Experienced", wikiUrl: "https://oldschool.runescape.wiki/w/Haunted_Mine" }),
  q({ name: "The Heart of Darkness", members: true, difficulty: "Experienced" }),
  q({ name: "The Lost Tribe", members: true, difficulty: "Intermediate" }),
  q({ name: "The Path of Glouphrie", members: true, difficulty: "Experienced" }),
  q({ name: "The Queen of Thieves", members: true, difficulty: "Intermediate" }),
  q({ name: "The Ribbiting Tale of a Lily Pad Labour Dispute", members: true, difficulty: "Novice" }),
  q({ name: "The Slug Menace", members: true, difficulty: "Intermediate" }),
  q({ name: "The Tourist Trap", members: true, difficulty: "Intermediate" }),
  q({ name: "Tower of Life", members: true, difficulty: "Novice" }),
  q({ name: "Tree Gnome Village", members: true, difficulty: "Intermediate" }),
  q({ name: "Tribal Totem", members: true, difficulty: "Intermediate" }),
  q({ name: "Troll Romance", members: true, difficulty: "Intermediate" }),
  q({ name: "Troll Stronghold", members: true, difficulty: "Intermediate" }),
  q({ name: "Twilight's Promise", members: true, difficulty: "Intermediate" }),
  q({ name: "Underground Pass", members: true, difficulty: "Experienced" }),
  q({ name: "Wanted!", members: true, difficulty: "Intermediate" }),
  q({ name: "Watchtower", members: true, difficulty: "Intermediate" }),
  q({ name: "Waterfall Quest", members: true, difficulty: "Intermediate" }),
  q({ name: "What Lies Below", members: true, difficulty: "Intermediate" }),
  q({ name: "Witch's House", members: true, difficulty: "Intermediate" }),
  q({ name: "Zogre Flesh Eaters", members: true, difficulty: "Intermediate" }),
];

export const QUESTS_ALPHABETICAL: QuestMeta[] = [...QUESTS].sort((a, b) =>
  a.name.localeCompare(b.name, "en", { sensitivity: "base" }),
);
