import type { QuestWalkthrough } from "../types";

export const aKingdomDivided: QuestWalkthrough = {
  startPoint: "Talk to Martin Holt at Kourend Castle entrance in Kingstown.",
  itemsRequired: [
    "Melee gear, food, prayer potions",
    "Normal spellbook with Fire Bolt runes (or stronger fire spell)",
    "Any axe",
    "Defence potion (3-4 doses)",
    "Volcanic sulphur",
    "Molten glass",
    "Dark essence block (or pickaxe + chisel)",
  ],
  recommended: [
    "Combat 70+",
    "43+ Prayer for protection",
    "Stamina/energy + antipoison",
    "Xeric's talisman, Games necklace, Kharedst's memoirs",
    "Fairy ring access",
  ],
  enemies: [
    "Judge of Yama (level 168)",
    "2 Assassins (level 132)",
    "Xamphur (level 239) — Protect from Magic",
    "Barbarian Warlord (level 91)",
  ],
  sections: [
    {
      title: "The disgraced councillor's escape",
      steps: [
        { text: "Talk to Martin Holt at Kourend Castle." },
        { text: "Talk to Commander Fullore inside the castle." },
        { text: "Investigate the house: search drawers and read the receipt." },
        { text: "Talk to Tomas Lawry by the roses." },
        { text: "Visit the Lovakengj pub and talk to Fuggy." },
        { text: "Go to Port Piscarilius and talk to Cabin Boy Herbert." },
        { text: "Defeat the Judge of Yama (level 168) — dodge fire waves, use melee." },
        { text: "Talk to Commander Fullore inside Kourend Castle after the cutscene, then return to Martin Holt at the castle entrance in Kingstown." },
        { text: "Teleport to Arceuus Library and pickpocket Istoria for a Bluish key." },
        { text: "Search the pink case for Rose's diary." },
        { text: "Return to Martin Holt at Kourend Castle entrance in Kingstown with the diary." },
      ],
    },
    {
      title: "Kourend's last princess",
      steps: [
        { text: "Go to the Forthos Ruins north-east of the Woodcutting Guild." },
        { text: "Search stone piles for number combinations." },
        { text: "Cut vines and enter the panel using code ROSE." },
        { text: "Show the note to Martin Holt." },
        { text: "Travel to the Settlement Ruins and talk to Martin in the north-west building." },
        { text: "Kill the spawned assassin." },
        { text: "Cast Fire Bolt on the ice chunks; search and open the panel." },
        { text: "Go to The Legless Faun in Piscarilius." },
        { text: "Check the panel upstairs and note the house order." },
        { text: "Push the statue panels in the correct order." },
        { text: "Search the bed in the shack for a tatty note." },
        { text: "Inspect the crates and climb down the trap door." },
      ],
    },
    {
      title: "The mysterious mage",
      steps: [
        { text: "Travel south to Molch." },
        { text: "Enter the Lizard dwelling and talk to Kaht B'alam." },
        { text: "Jump the hole to exit the temple." },
        { text: "Cross the stone bridge in Kebos Swamp." },
        { text: "Search south-eastern Lizardman eggs (triggers a brute attack)." },
        { text: "Return to the temple and give the egg to Kaht B'alam for a key." },
        { text: "Open the north wall door and defeat Xamphur (level 239) using Protect from Magic." },
        { text: "Search the northern table in the lab." },
        { text: "Return to the shack and go downstairs." },
        { text: "Talk to all 5 Lords at their respective locations." },
        { text: "Travel to Xeric's Lookout and talk to Commander Fullore." },
        { text: "Talk to all 5 Lords again on different floors." },
      ],
    },
    {
      title: "The council's end",
      steps: [
        { text: "Ask Commander Fullore about Lady Lovakengj." },
        { text: "Travel to Mount Karuulm and talk to Kaal-Mej-San." },
        { text: "Make a sulphur potion (defence potion + volcanic sulphur)." },
        { text: "Get the shielding potion from Kaal-Mej-San." },
        { text: "Pour the potion on the Doors of Dinh at the Wintertodt Camp." },
        { text: "Go to the Barbarian camp in Kourend Woodland; defeat the Barbarian Warlord (level 91)." },
        { text: "Talk to Phileas Rimor in his house north-west of the Hosidius Vinery." },
        { text: "Go to the prison west of the Graveyard of Heroes; talk to Martin Holt." },
        { text: "Go to the Graveyard of Heroes; talk to Jorra and kill the assassin." },
        { text: "Go to Arceuus church; give Mori molten glass + dark essence block." },
        { text: "Go to the Chasm of Fire and attempt entry." },
        { text: "Go to the Hosidius Vinery; inspect the wine barrel; pick the lock on the chest." },
        { text: "Return to Xeric's Lookout, west of Kourend Castle, and talk to all 5 Lords there." },
        { text: "Talk to Commander Fullore at Xeric's Lookout, west of Kourend Castle, for the final cutscene." },
        { text: "Quest complete." },
      ],
    },
  ],
  rewards: [
    "2 Quest Points",
    "Book of the Dead (Arceuus spellbook book item)",
    "2 antique lamps (10,000 XP each in any skill 40+)",
    "Ability to set respawn point at Kourend Castle",
    "24 new Arceuus spellbook spells",
    "Ability to fight Yama",
  ],
};
