import type { QuestWalkthrough } from "../types";

export const inAidOfTheMyreque: QuestWalkthrough = {
  startPoint: "Speak to Veliaf Hurtz in the cave hideout under the Hair of the Dog tavern in Canifis.",
  itemsRequired: [
    "Pickaxe",
    "Spade",
    "1-5 Buckets",
    "Hammer",
    "44 Nails",
    "11 Planks",
    "Swamp paste",
    "4 Tinderboxes",
    "10 Bronze axes",
    "10 Raw mackerel or snail meat",
    "2 Steel bars",
    "Coal",
    "Soft clay",
    "Silver bar",
    "Mithril bar",
    "Cut sapphire",
    "Rope",
    "Water rune + Cosmic rune (for Lvl-1 Enchant)",
    "Silver weapon (or Efaritay's aid) for vampyre damage",
  ],
  recommended: [
    "Combat 45+",
    "Steel armour and silver sickle for Ivan Strom",
    "15 cooked food items to give Ivan during Temple Trekking",
  ],
  enemies: [
    "Gadderanks (level 35) — safespot",
    "Vampyre Juvinates (multiple, level 50-75)",
  ],
  sections: [
    {
      title: "Travel to Burgh de Rott",
      steps: [
        { text: "Descend the trapdoor behind the Canifis pub and enter the Myreque cave." },
        { text: "Talk to Veliaf Hurtz in the cave hideout under the Hair of the Dog tavern in Canifis and accept his next assignment." },
        { text: "Travel south to Burgh de Rott (long walk through swamp)." },
      ],
    },
    {
      title: "Repair Burgh de Rott",
      steps: [
        { text: "Talk to Florin at the gate. Place food in the chest to enter." },
        { text: "Talk to Razvan near the pub." },
        { text: "Enter the pub, climb the broken wall, mine the rubble blocking a trapdoor." },
        { text: "Mine the remaining rubble in the basement and pick up fragments + scroll." },
        { text: "Use a spade to fill buckets with rubble; dump them on the pile outside." },
        { text: "Talk to Razvan again near the pub." },
        { text: "Talk to Aurel at the general store." },
        { text: "Repair the store roof (3 planks + 12 nails) and the wall (3 planks + 12 nails)." },
        { text: "Aurel gives you a crate — add 10 bronze axes, 10 mackerel/snails, 3 tinderboxes." },
        { text: "Talk to Cornelius at the bank. Repair the booth (2 planks + swamp paste + 8 nails) and wall (3 planks + 12 nails)." },
      ],
    },
    {
      title: "Defend the village",
      steps: [
        { text: "Talk to Razvan near the pub." },
        { text: "Repair the furnace using steel bars + coal + tinderbox." },
        { text: "Talk to Gadderanks in the general store." },
        { text: "Defeat Gadderanks and 2 Vampyre Juvinates with silver weapons." },
        { text: "Talk to Gadderanks again after the fight." },
        { text: "Talk to Veliaf Hurtz in the cave hideout under the Hair of the Dog tavern in Canifis." },
      ],
    },
    {
      title: "Escort Ivan via Temple Trekking",
      steps: [
        { text: "Return to the hideout under Canifis pub." },
        { text: "Talk to Polmafi Ferdygris." },
        { text: "(Optional) Equip Ivan Strom with steel armour and food." },
        { text: "Pick a Temple Trekking route (short or long) and escort Ivan to the Paterdomus temple." },
        { text: "Defeat any Vampyre Juvinates encountered along the way." },
        { text: "At the temple, talk to Drezel and get the cell key." },
        { text: "Use the key on the eastern wall keyhole, climb down the trapdoor." },
        { text: "Search the bookcases until you find 'The Sleeping Seven'. Read it." },
      ],
    },
    {
      title: "Make the Rod of Ivandis",
      steps: [
        { text: "Return to the blockaded cave entrance near Canifis." },
        { text: "Use a hammer on the wooden boards." },
        { text: "Use soft clay on the coffin to create a rod mould." },
        { text: "Travel to a furnace with the mould, silver bar, mithril bar, and cut sapphire." },
        { text: "Smelt to make a silvthrill rod." },
        { text: "Cast Lvl-1 Enchant on the rod." },
        { text: "Travel to the well beneath Paterdomus Temple with a rope." },
        { text: "Use the enchanted rod on the well to make the Rod of Ivandis." },
        { text: "Return to the Burgh de Rott pub basement and talk to Veliaf Hurtz." },
        { text: "Quest complete." },
      ],
    },
  ],
  rewards: [
    "2 Quest Points",
    "2,000 Attack / Strength / Defence / Crafting experience each",
    "Access to Burgh de Rott and Temple Trekking minigame",
    "Ability to craft the Rod of Ivandis",
    "5 Kudos at the Varrock Museum",
  ],
};
