import type { QuestWalkthrough } from "../types";

export const regicide: QuestWalkthrough = {
  startPoint: "Talk to King Lathas on the first floor of Ardougne Castle (after Underground Pass).",
  itemsRequired: [
    "5+ coal in your bank (25+ recommended)",
    "Bow and arrows",
    "2 ropes (3 if you fail)",
    "Spade",
    "Limestone (or pickaxe + 10 Mining)",
    "Tinderbox",
    "Strip of cloth (or 4 wool to make on a loom)",
    "Pestle and mortar",
    "Gloves",
    "Pot",
    "Cooked rabbit",
  ],
  recommended: [
    "Combat 60+",
    "Antidote++ or super antipoison",
    "Stamina potions",
    "Weight-reducing gear",
    "3+ Summer pies",
    "Ranged/magic for safespotting Tyras Guard",
  ],
  enemies: ["Tyras Guard (level 110) — safespottable"],
  sections: [
    {
      title: "Through the Underground Pass again",
      steps: [
        { text: "Talk to King Lathas on the first floor of Ardougne Castle (after Underground Pass)." },
        { text: "Navigate the Underground Pass with bow + arrows." },
        { text: "Use cloth-lit arrows to open the gate." },
        { text: "Cross gaps with rope; pull the lever; search the odd markings." },
        { text: "Dig the loose dirt; cross the ledge; use swamp shortcut or maze." },
        { text: "Squeeze the pipe; pass the tunnel; place a plank on the rocks." },
        { text: "(Optional) Charge Iban's staff at the Flames of Zamorak well." },
        { text: "Enter the well at Iban's temple and exit west." },
      ],
    },
    {
      title: "Traverse Isafdar",
      steps: [
        { text: "Run west through the forest, talking to Idris when she appears." },
        { text: "Jump the leaves trap, pass the sticks trap, reach the Iorwerth Camp." },
        { text: "Talk to Lord Iorwerth." },
        { text: "Follow the map to the Elf Tracker." },
        { text: "Talk to Lord Iorwerth at the Elf Camp twice; collect the crystal pendant from him." },
        { text: "Follow the tracks north-west of the blue mushrooms." },
        { text: "Defeat the Tyras Guard (level 110) — safespot available." },
        { text: "Reach General Hining's camp; collect 2-3 barrels." },
        { text: "Use barrels on the tar to make barrels of coal tar." },
        { text: "Collect a sulphur piece nearby." },
        { text: "Talk to Iorwerth about each item needed." },
      ],
    },
    {
      title: "Make the bomb materials",
      steps: [
        { text: "Use limestone on a furnace while wearing gloves to make quicklime." },
        { text: "Use pestle and mortar on quicklime with a pot." },
        { text: "Use pestle and mortar on the sulphur." },
        { text: "Make a strip of cloth at a loom (4 balls of wool)." },
      ],
    },
    {
      title: "Deadly chemistry",
      steps: [
        { text: "Travel to Rimmington and talk to the Chemist (must have his book in inventory)." },
        { text: "Un-note coal at the general store." },
        { text: "Use barrel of coal tar on the fractionalising still." },
        {
          text: "Operate the still: turn the tar valve right, wait for green pressure, then adjust left.",
        },
        { text: "Slowly add 2 coal, then 1 at a time as heat lowers." },
        { text: "Receive barrel of naphtha (make a second for safety)." },
        { text: "Use quicklime + sulphur on the naphtha barrel." },
        { text: "Use a strip of cloth on the bomb to finish it." },
      ],
    },
    {
      title: "Royal assassination and finish",
      steps: [
        { text: "Travel back through the Underground Pass with the bomb." },
        { text: "Cook a rabbit if needed." },
        { text: "Head north to the catapult near Tyras Camp." },
        { text: "Confirm a tinderbox is in your inventory." },
        { text: "Use the cooked rabbit on the guard near the catapult." },
        { text: "Use the bomb on the catapult." },
        { text: "Talk to Lord Iorwerth." },
        { text: "Try to enter Ardougne Castle, then talk to King Lathas." },
        { text: "Quest complete." },
      ],
    },
  ],
  rewards: [
    "3 Quest Points",
    "13,750 Agility experience",
    "15,000 coins",
    "Access to Tirannwn (Lletya, Isafdar, Tyras Camp, etc.)",
    "Ability to wield Dragon halberd",
    "Ship charter to Port Tyras (66 Sailing)",
    "Iorwerth camp + Zul-Andra teleport scrolls",
    "Fairy ring BJS access",
  ],
};
