import type { QuestWalkthrough } from "../types";

export const sinsOfTheFather: QuestWalkthrough = {
  startPoint: "Talk to Veliaf Hurtz outside the church in Slepe.",
  itemsRequired: [
    "Any axe",
    "Vyrewatch outfit (or 1,950 coins to buy)",
    "Ivandis flail",
    "Cut ruby",
    "Knife",
    "Chisel",
    "Runes for Lvl-3 Enchant (or enchant ruby tablet)",
  ],
  recommended: [
    "Combat 95+",
    "Drakan's medallion",
    "Pickaxe (20 Mining helps)",
    "Stamina, Antipoison, Prayer potions",
    "Sharks/anglers and combat gear",
    "Slayer helmet (works on Vanstrom in this quest)",
  ],
  enemies: [
    "Kroy (level 133)",
    "Nail beasts (level 67-143)",
    "Vampyre Juvinates (level 119-122)",
    "Mutated Bloodveld (level 123)",
    "Damien Leucurte (level 204)",
    "Vanstrom Klause (level 459) — boss",
  ],
  sections: [
    {
      title: "Slepe's sleeper plague",
      steps: [
        { text: "Talk to Veliaf Hurtz outside the church in Slepe." },
        { text: "Interview Hameln the Jester in the church." },
        { text: "Question Carl in the pub about the Bloody Bracers." },
        { text: "Follow Carl by hiding behind designated barrels until you witness the lab." },
        { text: "Defeat Kroy with ranged from behind the lab tables." },
        { text: "Destroy both lab tables." },
        { text: "Report back to Veliaf at the graveyard." },
        { text: "Meet Veliaf at Paterdomus by Drezel." },
        { text: "Talk to Ivan Strom south of Fenkenstrain's Castle." },
      ],
    },
    {
      title: "Escort Ivan again",
      steps: [
        { text: "Begin the trek with Ivan Strom east of Paterdomus." },
        { text: "Cut vines and create a long vine to cross the swamp." },
        { text: "Defeat Nail beasts and tend to Ivan's health as needed." },
        { text: "Build a bridge using logs to continue." },
        { text: "Defeat Vampyre Juvinates with the Ivandis flail." },
        { text: "Escort Ivan to the Burgh de Rott boathouse." },
      ],
    },
    {
      title: "Icyene Graveyard",
      steps: [
        { text: "Board the boat to Icyene Graveyard." },
        { text: "Talk to Vanescula Drakan in the Myreque Hideout under Old Man Ral?s house in Meiyerditch." },
        { text: "Solve the mausoleum door puzzle (rotate to align symbols)." },
        { text: "Interview the 5 Myreque members in the order Vanescula gives." },
        { text: "Teleport to the Ver Sinhaza mines." },
        { text: "Mine 15 Daeyalt ore." },
        { text: "Defeat the Mutated Bloodveld in the lab." },
        { text: "Retrieve a note from a bookshelf." },
        { text: "Return to Burgh de Rott and meet the Myreque at the pub." },
      ],
    },
    {
      title: "The Vyre noble disguise",
      steps: [
        { text: "Get the Vyrewatch outfit if you don't have one (1,950gp)." },
        { text: "Access the underground lair under Old Man Ral's house." },
        { text: "Upgrade the outfit to noble-tier with a tailor inside." },
        { text: "Return to Icyene Graveyard, then travel to Slepe." },
        { text: "Defeat Damien Leucurte with the Ivandis flail (stomp magical fires; use Protect from Magic)." },
        { text: "Report success to Veliaf." },
      ],
    },
    {
      title: "Branches of Darkmeyer",
      steps: [
        { text: "Equip the Vyre noble clothing." },
        { text: "Reach Darkmeyer via Ver Sinhaza." },
        { text: "Access the mines and navigate through the cracked wall." },
        { text: "Visit the Arboretum and interview the guard." },
        { text: "Talk to Mordan Nikazsi and Maria Gadderanks inside Burgh de Rott." },
        { text: "Read a note in the toppled shelves." },
        { text: "Configure the north and south valves per the solution." },
        { text: "Cut 8 blisterwood logs." },
      ],
    },
    {
      title: "Make the Blisterwood flail and defeat Vanstrom",
      steps: [
        { text: "Return to the underground lair with the blisterwood logs." },
        { text: "Give 7 logs to Vertida Sefalatis." },
        { text: "Get a silver sickle, attach a cut ruby, enchant it." },
        { text: "Attach a blisterwood log, then combine with the Ivandis flail to create the Blisterwood flail." },
        { text: "Defeat Vanstrom Klause (level 459) — manage Bloodveld summons, blood orb heals, and the darkness attack." },
        { text: "Watch the final cutscene." },
        { text: "Quest complete." },
      ],
    },
  ],
  rewards: [
    "2 Quest Points",
    "Access to Darkmeyer and the Daeyalt Essence Mine",
    "Blisterwood flail (best vampyre weapon)",
    "Tome of experience (usable 6 times — 15,000 XP each)",
    "Drakan's medallion teleport upgrade (Burgh de Rott / Slepe / Icyene Graveyard)",
  ],
};
